FROM ibmcom/websphere-traditional:8.5.5.20
COPY app.ear /work/config/app.ear
COPY install_app.py /work/config/install_app.py
COPY was-config.props /work/config/was-config.props
ENV ENABLE_BASIC_LOGGING=true
# RUN env JVM_EXTRA_CMD_ARGS=-Xnoloa /work/configure.sh
RUN /work/configure.sh
